[tool.ruff]
extend = "../pyproject.toml"

[tool.ruff.lint]
preview = true
extend-select = [
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "COM",   # flake8-commas
    "DTZ",   # flake8-datetimez
    "E",     # error
    "ERA",   # flake8-eradicate
    "F",     # pyflakes
    "FBT",   # flake8-boolean-trap
    "N",     # pep8-naming
    "PGH",   # pygrep-hooks
    "PIE",   # flake8-pie
    "RUF",   # ruff specific
    "SIM",   # flake8-simplify
    "T20",   # flake8-print
    "UP",    # pyupgrade
    "W",     # warning
]
ignore = ["COM812"]
